### ISSUE TITLE
feat: Add flag to blob copy action to disregard intermediate paths

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/actions#116]
Currently, the blob-copy action keeps intermediate paths when downloading files, so something like

```yml
      - name: Download Analysis Outputs
        id: download-analysis-outputs
        uses: RMI-PACTA/actions/actions/azure/blob-copy@main
        with:
          source: https://pactadatadev.blob.core.windows.net/container_name/some/long/path/foo
          destination: dest_dir
```

will write files to `dest_dir/some/long/path/foo` (including recursives, so `foo/a/b/c.txt` would be `dest_dir/some/long/path/foo/a/b/c.txt`)

Add an optional input to copy objects (files/dirs) directly to `$DESTINATION`, so that we would see `dest_dir/a/b/c.txt` instead.
