### ISSUE TITLE
Add docker comment action

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/actions#57]
Followup to #56 

We've previously had an action that added a comment to the PR thread with the docker image name, with a copiable `docker pull` command to make life easy.

Code for that here:
```yml
  add_comment:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        # https://github.com/peter-evans/find-comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Docker image from this PR

      - name: Create or update comment
        # https://github.com/peter-evans/create-or-update-comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Docker image from this PR (${{ github.event.pull_request.head.sha }}) created
            ```
            docker pull ${{ needs.build-docker-image.outputs.full-image-name }}
            ```
          edit-mode: replace
```
